# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-31 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(max_length=256)),
                ('reason', models.TextField(max_length=2058)),
            ],
        ),
    ]
