# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-31 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteplayer',
            name='player_name',
            field=models.CharField(max_length=256),
        ),
    ]
