# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-10 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FavFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='favfoods',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaApp.Person'),
        ),
        migrations.AddField(
            model_name='age',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaApp.Person'),
        ),
    ]
